### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by MonokuroInzanaito** [LuiCat/mc2tja#1]
When I clicked `Convert`, nothing came out on the right.
I really wish to play some charts on TaikoJiro, so I would be glad if it could be completed!

**Comment by LuiCat** [comment]
@MonokuroInzanaito , your issue cannot be confirmed without further info. Would you submit your chart here so that I can figure out what your problem is? Also, would you indicate if you loaded the chart via URL or by selecting a file? Finally, may I ask what browser are you using, since I only tested the online convert feature for Google Chrome?

**Comment by LuiCat** [comment]
Closing this issue for no more evidences are provided.
